security:
    # New Authenticator manager (default in 5.4+, only option in 6.0+).
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: CleanGutter\Entity\Tenant
                property: uuid
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: CleanGutter\Security\LoginFormAuthenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
