home:
    path: /
    controller: CleanGutter\Controller\DefaultController::index
login_get:
    path: /login
    controller: CleanGutter\Controller\SecurityController::getLogin
#kathleen:
#    path: /kathleen
#    controller: CleanGutter\Controller\DefaultController::city
#bonaire:
#    path: /bonaire
#    controller: CleanGutter\Controller\DefaultController::city
#perry:
#    path: /perry
#    controller: CleanGutter\Controller\DefaultController::city
#fort-valley:
#    path: /fort-valley
#    controller: CleanGutter\Controller\DefaultController::city