home:
    path: /
    controller: CleanGutter\Controller\DefaultController::getHome
landing-page:
    path: /landing-page
    controller: CleanGutter\Controller\DefaultController::getLandingPage
frequently-asked-questions:
    path: /faq
    controller: CleanGutter\Controller\DefaultController::getFaq

# SEO Controller
get_sitemap_xml:
    path: /sitemap.xml
    controller: CleanGutter\Controller\SeoController::getSitemapXml

#kathleen:
#    path: /kathleen
#    controller: CleanGutter\Controller\DefaultController::city
#bonaire:
#    path: /bonaire
#    controller: CleanGutter\Controller\DefaultController::city
#perry:
#    path: /perry
#    controller: CleanGutter\Controller\DefaultController::city
#fort-valley:
#    path: /fort-valley
#    controller: CleanGutter\Controller\DefaultController::city