home:
    path: /
    controller: CleanGutter\Controller\DefaultController::getHome
landing-page:
    path: /landing-page
    controller: CleanGutter\Controller\DefaultController::getLandingPage
frequently-asked-questions:
    path: /faq
    controller: CleanGutter\Controller\DefaultController::getFaq
about-us:
    path: /about
    controller: CleanGutter\Controller\DefaultController::getAbout
contact:
    path: /contact
    controller: CleanGutter\Controller\DefaultController::getContact
terms-of-service:
    path: /terms-of-service
    controller: CleanGutter\Controller\DefaultController::getTermsOfService
privacy-policy:
    path: /privacy-policy
    controller: CleanGutter\Controller\DefaultController::getPrivacyPolicy

# SEO Controller
get_sitemap_xml:
    path: /sitemap.xml
    controller: CleanGutter\Controller\SeoController::getSitemapXml

#kathleen:
#    path: /kathleen
#    controller: CleanGutter\Controller\DefaultController::city
#bonaire:
#    path: /bonaire
#    controller: CleanGutter\Controller\DefaultController::city
#perry:
#    path: /perry
#    controller: CleanGutter\Controller\DefaultController::city
#fort-valley:
#    path: /fort-valley
#    controller: CleanGutter\Controller\DefaultController::city